CREATE TABLE USERS(
    ID INT PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(256) NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    REGISTRATION DATE
);

/

CREATE TABLE SEMESTERS(
    ID INT PRIMARY KEY,
    NAME VARCHAR2(30)
);

/

CREATE TABLE SUBJECTS(
    CODE VARCHAR2(10) PRIMARY KEY,
    NAME VARCHAR2(150) NOT NULL,
    SEMESTER_ID INT REFERENCES SEMESTERS(ID)
);

/

CREATE TABLE USERS_SUBJECTS(
    USER_ID INT REFERENCES USERS(ID),
    SUBJECT_CODE VARCHAR2(10) REFERENCES SUBJECTS(CODE),
    CHECKED INT DEFAULT 0,
    PRIMARY KEY (USER_ID, SUBJECT_CODE)
);