CREATE OR REPLACE TRIGGER AUTO_SEQUENCE_USERS
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  SELECT USER_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE OR REPLACE TRIGGER AUTO_SEQUENCE_SEMESTERS
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  SELECT SEMESTER_SEQUENCE.NEXTVAL INTO :NEW.ID FROM DUAL;
END;