CREATE OR REPLACE PROCEDURE DELETE_RELATIONSHIP_USER_SUBJECT(
    P_USER_ID IN USERS.ID%TYPE,
    P_SUBJECT_CODE IN SUBJECTS.CODE%TYPE
)
AS
    RELATIONSHIP_COUNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO RELATIONSHIP_COUNT
    FROM USERS_SUBJECTS
    WHERE USER_ID = P_USER_ID
    AND SUBJECT_CODE = P_SUBJECT_CODE;

    IF RELATIONSHIP_COUNT > 0 THEN
        DELETE FROM USERS_SUBJECTS
        WHERE USER_ID = P_USER_ID
        AND SUBJECT_CODE = P_SUBJECT_CODE;

        COMMIT;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END;